model_name: 'BasicResNet'
data_dir: /home/jguinelli/mestrado/era5/dataset/5.625deg/
in_vars: {'geopotential': ('z', [50, 250, 500, 600, 700, 850, 925]), 'temperature': ('t', [50, 250, 500, 600, 700, 850, 925]), 'u_component_of_wind': ('u', [50, 250, 500, 600, 700, 850, 925]), 'v_component_of_wind': ('v', [50, 250, 500, 600, 700, 850, 925]), 'specific_humidity': ('q', [50, 250, 500, 600, 700, 850, 925]), 'toa_incident_solar_radiation': ('tisr', None), '2m_temperature': ('t2m', None), 'constants': ['lsm','orography','lat2d']}
out_vars: [t_850, z_500, t2m]
filters: [128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 3]
kernels: [7, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
bn_position: post
dropout: 0.1
lead_time: 120
nt_in: 3
dt_in: 6
discard_first: 24